version: '3.8'

networks:
  cicd_network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      - cicd_network
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - cicd_network
    restart: unless-stopped

  openvidu:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu
    ports:
      - "4443:4443"
      - "40000-40400:40000-40400/tcp"
      - "40000-40400:40000-40400/udp"
    environment:
      # OpenVidu 설정
      # # - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP}
      # - DOMAIN_OR_PUBLIC_IP=talktalkcare.com
      # - OPENVIDU_URL=${OPENVIDU_URL}
      # - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      # # - CERTIFICATE_TYPE=${CERTIFICATE_TYPE}
      # - CERTIFICATE_TYPE=selfsigned
      # - OPENVIDU_RECORDING=false
      # - HTTPS_PORT=443
      - DOMAIN_OR_PUBLIC_IP=talktalkcare.com
      - OPENVIDU_URL=https://localhost:4443
      - OPENVIDU_SECRET=talktalkcare
      - CERTIFICATE_TYPE=selfsigned
      - OPENVIDU_RECORDING=false
      - HTTPS_PORT=4443
    env_file:
      - .env
    volumes:
      - ./openvidu_data:/opt/openvidu/recordings
      - ./.env:/.env
    networks:
      - cicd_network
    restart: unless-stopped

  backend:
    image: eoslovy/talktalkcare-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - DB_DRIVER=${DB_DRIVER}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL}
      - JPA_DDL_AUTO=${JPA_DDL_AUTO}
      - JPA_FORMAT_SQL=${JPA_FORMAT_SQL}
      - JPA_DIALECT=${JPA_DIALECT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOG_LEVEL_SQL=${LOG_LEVEL_SQL}
      - LOG_LEVEL_TYPE=${LOG_LEVEL_TYPE}
      # OpenVidu 설정
      - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP}
      - OPENVIDU_URL=${OPENVIDU_URL}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      - CERTIFICATE_TYPE=${CERTIFICATE_TYPE}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      openvidu:
        condition: service_started
    networks:
      - cicd_network
    restart: on-failure:3

  nginx:
    image: eoslovy/talktalkcare-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - cicd_network
    restart: on-failure:3